version: "3"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis-data:/var/lib/redis
  web:
    image: teddit/teddit
    restart: unless-stopped
    logging:
      driver: none
    depends_on:
      - redis
    expose:
      - "8080"
    environment:
      - REDIS_HOST=redis
      - DOMAIN=teddit.namazso.eu
      - TRUST_PROXY=true
      - CACHE_CONTROL=true
      - CACHE_MAX_SIZE=100000
      - DOMAIN_REPLACEMENTS=[["m.youtube.com", "invidious.namazso.eu"],  ["youtube.com", "invidious.namazso.eu"],  ["img.youtube.com", "invidious.namazso.eu"],  ["www.youtube.com", "invidious.namazso.eu"],  ["youtube-nocookie.com", "invidious.namazso.eu"],  ["www.youtube-nocookie.com", "invidious.namazso.eu"],  ["youtu.be", "invidious.namazso.eu"],  ["s.ytimg.com", "invidious.namazso.eu"],  ["music.youtube.com", "invidious.namazso.eu"],  ["twitter.com", "nitter.namazso.eu"],  ["www.twitter.com", "nitter.namazso.eu"],  ["mobile.twitter.com", "nitter.namazso.eu"],  ["pbs.twimg.com", "nitter.namazso.eu"],  ["video.twimg.com", "nitter.namazso.eu"]]
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=teddit.namazso.eu
      - LETSENCRYPT_HOST=teddit.namazso.eu
    networks:
      - default
      - public_services

networks:
  public_services:
    external: true
