version: "3"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis-data:/var/lib/redis
  web:
    image: teddit/teddit
    restart: unless-stopped
    logging:
      driver: none
    depends_on:
      - redis
    expose:
      - "8080"
    environment:
      - REDIS_HOST=redis
      - DOMAIN=teddit.namazso.eu
      - TRUST_PROXY=true
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=teddit.namazso.eu
      - LETSENCRYPT_HOST=teddit.namazso.eu
    networks:
      - default
      - public_services

networks:
  public_services:
    external: true
