version: "3"
services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    
  lufi:
    image: namazso/lufi
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./files:/files
      - ./lufi.conf:/lufi/lufi.conf:ro
    expose:
      - "8081"
    environment:
      - VIRTUAL_PORT=8081
      - VIRTUAL_HOST=lufi.namazso.eu
      - LETSENCRYPT_HOST=lufi.namazso.eu
    networks:
      - default
      - public_services

networks:
  public_services:
    external: true
