version: '3'
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis-data:/var/lib/redis

  nitter:
    image: zedeus/nitter
    restart: unless-stopped
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://127.0.0.1:8080/namazso"]
    volumes:
      - ./nitter.conf:/src/nitter.conf:ro
    expose:
      - "8080"
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=nitter.namazso.eu
      - LETSENCRYPT_HOST=nitter.namazso.eu
    depends_on:
      - redis
    networks:
      - default
      - public_services

networks:
  public_services:
    external: true
